name: Build and Push Docker Images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
    
      - name: Set DOCKER_DEFAULT_PLATFORM
        run: echo "DOCKER_DEFAULT_PLATFORM=linux/amd64" >> $GITHUB_ENV
    
      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/mrcord/ml_churn/ml_churn-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/app
          file: ./frontend/app/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/mrcord/ml_churn/ml_churn-frontend:latest